# Generated by Django 4.1.3 on 2022-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('EmergencyContact', models.CharField(max_length=10)),
                ('BloodGroup', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('WorkLocation', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=200)),
                ('MaritalStatus', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50)),
            ],
        ),
    ]
