# Generated by Django 4.1.3 on 2022-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=100)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('CreatedDate', models.DateField()),
                ('ApprovalStatus', models.CharField(max_length=100)),
                ('AssignedManager', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
